source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'AFNetworkActivityLogger'
pod 'JSONModel'
pod 'JSQMessagesViewController'
pod 'SDWebImage', '~>3.6'