source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'AFNetworkActivityLogger'
pod 'JSONModel'
pod 'JSQMessagesViewController'
pod 'SDWebImage', '~>3.6'
pod 'AWSiOSSDKv2'
pod 'AWSCognitoSync'
pod 'CRToast', '~> 0.0.7'
pod 'M13Checkbox', '~> 1.1.0'
pod 'SVProgressHUD'
pod 'BBBadgeBarButtonItem'